{% set name = "kcrash" %}
{% set version = "5.65.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kcrash-{{ version }}.tar.xz
  sha256: 6b05608507dd2f8821399c4596021bcf9da79a284726a093c8b81b6d3cc4e034

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kcrash', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libx11
    - xorg-libxext
    - xcb-util-keysyms
    - qt
    - kcoreaddons
    - kwindowsystem
  run:
    - xorg-libx11

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Crash.so

about:
  home: https://api.kde.org/frameworks/kcrash/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: 'Graceful handling of application crashes'
  description: |
    KCrash provides support for intercepting and handling application crashes.
  dev_url: https://cgit.kde.org/kcrash.git/tree

extra:
  recipe-maintainers:
    - scopatz
