{% set name = "kcrash" %}
{% set version = "5.75.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kcrash-{{ version }}.tar.xz
  sha256: 1c8950bf699e4df86c2ebe29a364be53017b45d127c1d052c7ac4ef13b96db3a

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kcrash', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libx11
    - xorg-libxext
    - xcb-util-keysyms
    - qt
    - kcoreaddons >={{ version }}
    - kwindowsystem >={{ version }}
  run:
    - xorg-libx11

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Crash.so

about:
  home: https://api.kde.org/frameworks/kcrash/html/index.html
  license: LGPL-2.0-or-later
  license_file: LICENSES/LGPL-2.0-or-later.txt
  summary: Graceful handling of application crashes
  description: |
    KCrash provides support for intercepting and handling application crashes.
  dev_url: https://cgit.kde.org/kcrash.git/tree

extra:
  recipe-maintainers:
    - scopatz
